Add files via upload

diff --git a/tarea2/Makefile b/tarea2/Makefile
--- a/tarea2/Makefile
+++ b/tarea2/Makefile
@@ -28,7 +28,7 @@
 all: principal
 
 # Objetivos que no son archivos.
-.PHONY: all clean_bin clean_test clean testing entrega
+.PHONY: all clean_bin clean_test clean testing entrega uso_memoria
 
 MODULOS = utils info cadena usoTads
 
@@ -45,7 +45,7 @@ EXT = cpp
 CC = g++ # gcc -x c 
 LD = g++ # gcc
 # opciones de compilación
-CCFLAGS = -Wall -Werror -I$(HDIR) -g  -DNDEBUG
+CCFLAGS = -Wall -Werror -I$(HDIR) -g  #-DNDEBUG
 # -DNDEBUG
 # se agrega esta opción para que las llamadas a assert no hagan nada.
 
@@ -66,30 +66,62 @@ $(ODIR)/$(PRINCIPAL).o:$(PRINCIPAL).$(EXT)
 	@printf 'Compilando $(<) \n'; \
 	$(CC) $(CCFLAGS) -c $< -o $@
 
+# cada .o depende de su .c
+
+$(ODIR)/%.o: $(CPPDIR)/%.$(EXT) $(HDIR)/%.h
+	$(CC) $(CCFLAGS) -c $< -o $@
+
+# $^ se expande para tranformarse en todas las dependencias
+$(EJECUTABLE): $(ODIR)/$(PRINCIPAL).o $(OS)
+	$(LD) $(CCFLAGS) $^ -o $@
+	
+# casos de prueba
+CASOS = 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 
 
 
+# cadena de archivos, con directorio y extensión
+INS=$(CASOS:%=$(TESTDIR)/%.in)
+OUTS=$(CASOS:%=$(TESTDIR)/%.out)
+SALS=$(CASOS:%=$(TESTDIR)/%.sal)
+DIFFS=$(CASOS:%=$(TESTDIR)/%.diff)
 
-$(ODIR)/%.o: $(CPPDIR)/%.$(EXT)  $(HDIR)/%.h
-	@printf 'Compilando $(<) \n'; \
-	$(eval resr = $(shell grep -n -P '_rep_(?!$(basename $(notdir $<)))' $<)) \
-	$(eval resh = $(subst #,\#,$(shell grep -n -P 'include(?!.*[.]h)' $< ))) \
-	$(eval resc = $(shell grep -n 'nodoCadena' $< )) \
-	if [ -z "$(resr)" ] && [ -z "$(resh)" ] && { [ -z "$(resc)" ] || [ -n "$(findstring cadena, $<)" ] ; }; \
-	then $(CC) $(CCFLAGS) -c $< -o $@ ; \
-	else \
-		if [ -n "$(resh)" ]; then printf '  "$(resh)": Include de archivos que no son .h \n' ; fi ; \
-		if [ -n "$(resr)" ]; then printf '  "$(resr)": Uso de representación de otros tipos\n' ; fi ; \
-		if [ -n "$(resc)" ]; then printf '  "$(resc)": Uso de nodoCadena\n' ; fi ; \
-		printf '    NO SE COMPILO $(<)\n' ; \
-		rm -f $@; \
+$(SALS):$(EJECUTABLE)
+# el guión antes del comando es para que si hay error no se detenga la
+# ejecución de los otros casos
+$(TESTDIR)/%.sal:$(TESTDIR)/%.in
+	-timeout 4 valgrind -q --leak-check=full ./$(EJECUTABLE) < $< > $@ 2>&1
+	@if [ $$(stat -L -c %s $@) -ge 10000 ]; then \
+		echo "tamaño excedido" > $@;\
 	fi
 
 
-# $^ se expande para tranformarse en todas las dependencias
-$(EJECUTABLE):$(ODIR)/$(PRINCIPAL).o $(OS)
-	@printf 'Compilando y enlazando $(@) \n'; \
-	$(LD) $(CCFLAGS) $^ -o $@
+%.diff:Makefile
+# cada .diff depende de su .out y de su .sal
+%.diff: %.out %.sal
+	@diff $^ > $@;                                            \
+	if [ $$? -ne 0 ];                                         \
+	then                                                      \
+		echo ---- ERROR en caso $@ ----;                  \
+	fi
+# Con $$? se obtiene el estado de salida del comando anterior.
+# En el caso de `diff', si los dos archivos comparados no son iguales,
+# el estado de la salida no es 0 y en ese caso se imprime el mensaje.
 
+
+
+
+# Test general. Las dependencias son los .diff.
+# Con `find` se encuentran los .diff de tamaño > 0 que están en el directorio
+# $(TESTDIR) y lo asigna a $(LST_ERR).
+# Si el tamaño de $(LST_ERR) no es cero imprime los casos con error.
+# Con `sed` se elimina el nombre de directorio y la extensión.
+testing:all $(DIFFS)
+	@LST_ERR=$$(find $(TESTDIR) -name *.diff* -size +0c -print);             \
+	if [ -n "$${LST_ERR}" ];                                                \
+	then                                                                    \
+		echo -- CASOS CON ERRORES --;                                   \
+		echo "$${LST_ERR}" | sed -e 's/$(TESTDIR)\///g' -e 's/.diff//g';\
+	fi
 
 # Genera el entregable.
 ENTREGA=Entrega2.tar.gz
@@ -115,3 +147,5 @@ clean:clean_test clean_bin
 
 
 
+check-syntax:
+	gcc -o nul -S ${CHK_SOURCES}
